In [1]:

def log_reg():
    import pandas as pd
    import numpy as np
    import matplotlib.pyplot as plt
    import seaborn as sns

    df = pd.read_csv('ATP Dataset_2012-01 to 2017-07_Int_V4.csv')  ### Read the file 
    match_df = pd.DataFrame(df)                                    ### making the dataframe
    #match_df.head()

    list1 = list(df['Player1_Odds'])                            
    list2 = list(df['Player2_Odds'])
    for i in range(len(list1)):
        if(list1[i]>list2[i]):
            list1[i] = 1
            list2[i] = 0
        else:                             #####Player ODDS conversion into P_odds   convertion to 0 and 1 classes
            list1[i] = 0
            list2[i] = 1
    df['P1_odds'] = pd.Series(list1)
    df['P2_odds'] = pd.Series(list2)


    list1 = list(df['Player1_Implied_Prob'])
    list2 = list(df['Player2_Implied_Prob'])
    for i in range(len(list1)):
        if(list1[i]>list2[i]):
            list1[i] = 1
            list2[i] = 0
        else:                           #####player_implied_probability conversion to 0 and 1
            list1[i] = 0
            list2[i] = 1
    df['P1_ip'] = pd.Series(list1)
    df['P2_ip'] = pd.Series(list2)

    #df.head()
 
    surface_bin = pd.get_dummies(df['Surface'])    ### Surface type with Binary value
    df = pd.concat([df,surface_bin],axis=1)

    bestof_bin = pd.get_dummies(df['Best_of'])     ### best of type with Binary value
    df =pd.concat([df,bestof_bin],axis=1)

    ##Drop all the unwanted
    df1 = df.drop(['Player1_Odds','Player2_Odds','Player1_Implied_Prob','Player2_Implied_Prob','Surface','Surface_Int','Date','Best_of'],axis = 1)  

##df.isnull().sum()
    df1.dropna(inplace=True)



    list1 = list(df1['P1_odds'])
    P_odd = []
    for i in range(len(list1)):
        if df['P1_odds'][i] == 1:
            P_odd.append(0)
        else:                                           #### Please check the Graph 
            P_odd.append(1)
    df1['Player_1_won'] = pd.Series(P_odd)



    list1 = list(df1['P2_odds'])
    P2_odd = []
    for i in range(len(list1)):
        if df['P2_odds'][i] == 1:
            P2_odd.append(0)
        else:
            P2_odd.append(1)
    df1['Player_2_won'] = pd.Series(P2_odd)


    df1 = df1.drop(['Winner_Int', 'Player1_Int','Player2_Int','Round','Court','Series','Tournament','Winner','Player1','Player2'],axis = 1)   
    df1.dropna(inplace=True)




    X = df1.drop(['P1_ip','P2_ip'],axis=1)    ### setting independant Var
    Y = df1['P1_ip']                          ### setting dependent variable 

    df1.head()
    from sklearn.model_selection import train_test_split
    X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.2 , random_state = 0)

    from sklearn.tree import DecisionTreeClassifier
    classifier_entropy = DecisionTreeClassifier(criterion = 'entropy', random_state = 0, max_depth = 3 , min_samples_leaf = 5)

    #create the model
    classifier_entropy.fit(X_train,Y_train)

    y_pred = classifier_entropy.predict(X_test)
    print(y_pred)

    from sklearn.metrics import accuracy_score
    print("Accuracy is" , accuracy_score(Y_test,y_pred)*100)


    from sklearn.metrics import confusion_matrix
    res = confusion_matrix(Y_test,y_pred)
    print("the confusion matrix is :  \n",res)


    prec = res[0,0]/(res[0,0]+res[0,1])
    print("Precall value of : ",prec)

    rec = res[0,0]/(res[0,0]+res[1,0])
    print("Recall value : ",rec)

def d_tree():
    import pandas as pd
    import numpy as np
    import seaborn as sns
    import matplotlib.pyplot as plt

    df = pd.read_csv("ATP Dataset_2012-01 to 2017-07_Int_V4.csv")
    temp_list1 = list(df['Player1_Odds'])
    temp_list2 = list(df['Player2_Odds'])


    for i in range(len(temp_list1)):
        if(temp_list1[i] > temp_list2[i]):
            temp_list1[i] = 1
            temp_list2[i] = 0
        else:
            temp_list1[i] = 0
            temp_list2[i] = 1
        
        
    df["P1_Odds"] = pd.Series(temp_list1) 
    df["P2_Odds"] = pd.Series(temp_list2)



    temp_list1 = list(df['Player1_Implied_Prob'])
    temp_list2 = list(df['Player2_Implied_Prob'])

    for i in range(len(temp_list1)):
        if(temp_list1[i] > temp_list2[i]):
            temp_list1[i] = 1
            temp_list2[i] = 0
        else:
            temp_list1[i] = 0
            temp_list2[i] = 1
    df["P1_IP"] = pd.Series(temp_list1)
    df["P2_IP"] = pd.Series(temp_list2)

    df1 = df.drop(['Player1_Odds','Player2_Odds','Player1_Implied_Prob','Player2_Implied_Prob'],axis = 1)
    Surf = pd.get_dummies(df['Surface'])
    df1 = pd.concat([df1,Surf],axis=1)
     #print(df1)
    df2 = df1.drop(['Surface','Surface_Int'],axis = 1)
    df2 = df2.drop(['Date'],axis = 1)

    best_of_01 = pd.get_dummies(df['Best_of'],drop_first = True)
    df2 = pd.concat([df2,best_of_01],axis = 1)
    df2.head(5)
    df2 = df2.drop(['Best_of'],axis = 1)
    df2.head(5)

   # df2['Player1_Rank'] = df['Player1_Rank'].astype(pd.Int32Dtype())   
    #df2['Player2_Rank'] = df['Player2_Rank'].astype(pd.Int32Dtype())
    #df2.head()

    df2  = df2.drop(['Player1','Player2','Winner','Round','Court','Series','Tournament','Player1_Rank','Player2_Rank'],axis = 1)


    list1 = list(df2['P1_Odds'])
    p1_list = []
    for i in range(len(df2['P1_Odds'])):
        if df['P1_Odds'][i] == 1:
            p1_list.append(0)
        else:
            p1_list.append(1)
#print("the next p1_odd list:",p1_list)


    list2 = list(df2['P2_Odds'])
    p2_list = []
    for i in range(len(df2['P2_Odds'])):
        if df['P2_Odds'][i] == 1:
            p2_list.append(0)
        else:
            p2_list.append(1)
    #print('the next p2_odd list: ',list2)


    df2['Player1_win?'] = pd.Series(list2)
    df2['Player2_win?'] = pd.Series(list1)

    df2 = df2.drop(['Winner_Int', 'Player1_Int','Player2_Int'],axis = 1)
    #df2.head(5)

    X = df2.drop(['P1_IP','P2_IP'],axis =1 )
    ###print(X)   
    Y = df2['P1_IP']


    from sklearn.model_selection import train_test_split
    X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.3 , random_state = 0)

    from sklearn.tree import DecisionTreeClassifier
    classifier_entropy = DecisionTreeClassifier(criterion = 'entropy', random_state = 0, max_depth = 3 , min_samples_leaf = 5)

    #create the model
    classifier_entropy.fit(X_train,Y_train)

    y_pred = classifier_entropy.predict(X_test)
    print(y_pred)

    from sklearn.metrics import accuracy_score
    print("Accuracy is" , accuracy_score(Y_test,y_pred)*100)

    from sklearn.metrics import confusion_matrix
    res = confusion_matrix(Y_test,y_pred)
    print("CONFUSION MATRIX IS : \n",res)

    prec = res[0,0]/(res[0,0]+res[0,1])
    print("the Precision of this model : ",prec)

    rec = res[0,0]/(res[0,0]+res[1,0])
    print("The recall Value is : ",rec)
    F1score = 2*prec*rec/(prec+rec)
    print("The F1 score of the model : ",F1score)
def knn():
    import pandas as pd
    from sklearn.model_selection import train_test_split                  #### No edit only space removed
    from sklearn.preprocessing import StandardScaler
    from sklearn.neighbors import KNeighborsClassifier
    from sklearn.metrics import confusion_matrix
    from sklearn.metrics import f1_score
    from sklearn.metrics import accuracy_score
    import seaborn as sns
    import numpy as np

    df = pd.read_csv("ATP Dataset_2012-01 to 2017-07_Int_V4.csv")
    df.head()
    temp_list1 = list(df['Player1_Implied_Prob'])
    ##sns.boxplot(df['Player2_Odds'])
    temp_list2 = list(df['Player2_Implied_Prob'])

    for i in range(len(temp_list1)):
        if(temp_list1[i] > temp_list2[i]):
            temp_list1[i] = 1
            temp_list2[i] = 0
        else:
            temp_list1[i] = 0
            temp_list2[i] = 1
        
    df["P1_IP"] = pd.Series(temp_list1) 
    df["P2_IP"] = pd.Series(temp_list2)

    Surf = pd.get_dummies(df['Surface'])
    df = pd.concat([df,Surf],axis=1)
    df = df.drop(['Surface','Surface_Int'],axis = 1)    ### surface drop  ...surface--->surf
    df = df.drop(['Date'],axis = 1)


    best_of_01 = pd.get_dummies(df['Best_of'],drop_first = True)   ### best_of --> best_of_01 and drop
    df = pd.concat([df,best_of_01],axis = 1)
    df = df.drop(['Best_of'],axis = 1)


    df['Player1_Rank'] = df['Player1_Rank'].astype(pd.Int32Dtype())
    df['Player2_Rank'] = df['Player2_Rank'].astype(pd.Int32Dtype())


    df = df.drop(['Player1_Rank','Player2_Rank'],axis = 1)
    df = df.drop(['Player1','Player2','Winner'],axis = 1)

    df = df.drop(['Round','Court','Series'],axis = 1)
    df = df.drop(['Tournament'],axis = 1)
    df = df.drop(['Winner_Int', 'Player1_Int','Player2_Int'],axis = 1)

    X = df.drop(['P1_IP','P2_IP',],axis =1 )
    ##print(X)
    Y = df['P1_IP']

    from sklearn.model_selection import train_test_split
    X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.3 , random_state = 100)

    #print(math.sqrt(len(X_test)))
    classifier = KNeighborsClassifier(n_neighbors = 19,p=2,metric = 'euclidean')
    classifier.fit(X_train,Y_train)

    y_pred = classifier.predict(X_test)
    print("Prediction : ",y_pred)

    cm = confusion_matrix(Y_test,y_pred)
    print(cm)

    print("f1score",f1_score(Y_test,y_pred))
    from sklearn.metrics import accuracy_score
    print("Accuracy is" , accuracy_score(Y_test,y_pred)*100)


def n_b():
    from sklearn.naive_bayes import GaussianNB
    import numpy as np
    import pandas as pd
    df = pd.read_csv('ATP Dataset_2012-01 to 2017-07_Int_V4.csv')
    df = pd.DataFrame(df)
    df.head(5)
    df.drop('Tournament',axis=1,inplace=True)
    df.drop('Series',axis=1,inplace=True)
    df.drop('Surface',axis=1,inplace=True)
    df.drop('Court',axis=1,inplace=True)
    df.drop('Court_Int',axis=1,inplace=True)
    df.drop('Round',axis=1,inplace=True)
    df.drop('Round_Int',axis=1,inplace=True)
    df.drop('Player1',axis=1,inplace=True)
    df.drop('Player2',axis=1,inplace=True)
    df.dropna(inplace=True)
    df.head(10)
    df.drop('Date',axis=1,inplace=True)
    df.drop('Winner',axis=1,inplace=True)
    df.head(10)
    list1=list(df['Player1_Implied_Prob'])
    list2=list(df['Player2_Implied_Prob'])
    for i in range(len(list1)):
        if(list1[i]>list2[i]):
            list1[i]=1
            list2[i]=0
        else:
            list1[i]=0
            list2[i]=1

    df['p1_ip']=pd.Series(list1)

    df['p2_ip']=pd.Series(list2)
    df1=df.drop(['Player1_Implied_Prob','Player2_Implied_Prob'],axis=1)
    df.drop('Player1_Implied_Prob',axis=1,inplace=True)
    df.drop('Player2_Implied_Prob',axis=1,inplace=True)
    df.head(10)
    tlist1=list(df['Player1_Odds'])
    tlist2=list(df['Player2_Odds'])
    for i in range(len(tlist1)):
        if(tlist1[i]>tlist2[i]):
            tlist1[i]=1
            tlist2[i]=0
        else:
            tlist1[i]=0
            tlist2[i]=1

    df['p1_odds']=pd.Series(tlist1)

    df['p2_odds']=pd.Series(tlist2)
    df.drop('Player1_Odds',axis=1,inplace=True)
    df.drop('Player2_Odds',axis=1,inplace=True)
    df.head(10)
    list3=list(df['p1_odds'])
    list4=list(df['p2_odds'])
    list5 = list(df['p1_ip'])
    list6 = list(df['p2_ip'])
    list7 = list(df['Winner_Int'])
    list8 = list(df['Player1_Int'])
    list9 = list(df['Player2_Int'])
    features = pd.DataFrame()
    features['p1_odds'] = pd.Series(list3)
    features['p2_odds'] = pd.Series(list4)
    features['Winner_Int'] = pd.Series(list7)
    features['Player1_Int'] = pd.Series(list8)
    features['Player2_Int'] = pd.Series(list9)
    features.dropna(inplace=True)
    list1 = []
    list2 = []
    for i in range(len(features['p1_odds'])):
        if features['Winner_Int'][i] == features['Player1_Int'][i]:
            list1.append(1)
            list2.append(0)
        else:
            list2.append(1)
            list1.append(0)
    features['Pw1'] = pd.Series(list1)
    features['Pw2'] = pd.Series(list2)
    label = pd.DataFrame()
    label['p1_ip'] = pd.Series(list5)
    label.dropna(inplace=True)
     #print(label.head())
    features = features.drop(['Winner_Int','Player1_Int','Player2_Int'],axis = 1)
    print(features.head())
    from sklearn.naive_bayes import GaussianNB
    model=GaussianNB() #create a gaussian classifier
    model.fit(features,label)   #train the model using training sets
    predicted=model.predict([[0,1,1,0]])
    print("predicted value:",predicted)
    
    
    
i=0    
option = ['1.log_reg','2.D tree','3.Knn','4.Naive Bayes','5.Exit']
for each in option:
    print(each)
while(i==0):
    dec = int(input("Enter your choice - "))
    if dec==1:
        log_reg()
    elif dec == 2:
        d_tree()
    elif dec == 3:
        knn()
    elif dec == 4:
        n_b()
    elif dec == 5:
        i=1
    else:
        print('wrong choice')

1.log_reg
2.D tree
3.Knn
4.Naive Bayes
5.Exit
Enter your choice - 1
[1 1 0 ... 1 1 1]
Accuracy is 99.89768076398363
the confusion matrix is :  
 [[1470    3]
 [   0 1459]]
Precall value of :  0.9979633401221996
Recall value :  1.0
Enter your choice - 2
[1 1 0 ... 1 0 1]
Accuracy is 99.88690341551685
CONFUSION MATRIX IS : 
 [[2248    5]
 [   0 2168]]
the Precision of this model :  0.9977807367953839
The recall Value is :  1.0
The F1 score of the model :  0.9988891357476116
Enter your choice - 3
Prediction :  [0 0 0 ... 0 1 1]
[[2215   32]
 [  39 2135]]
f1score 0.9836443215848882
Accuracy is 98.39402850033929
Enter your choice - 


ValueError: invalid literal for int() with base 10: ''